### ISSUE TITLE
I'm having an issue setting up a basic FGSM attack

### ISSUE THREAD

**Issue by shamoons** [tensorflow/cleverhans#1081]
I apologize if this seems basic. But I'm trying to save MNIST images that have been attacked with FGSM. My code is:
```
import argparse
import tensorflow as tf
from cleverhans.dataset import MNIST
from cleverhans.attacks import FastGradientMethod
from cleverhans.model_zoo.basic_cnn import ModelBasicCNN

parser = argparse.ArgumentParser()
parser.add_argument('--attack', required=True,
                    choices=['fgsm'])

args = parser.parse_args()
sess = tf.Session(config=tf.ConfigProto())


if args.attack == 'fgsm':
    model = ModelBasicCNN('model1', 10, 64)
    attack = FastGradientMethod(model, sess=sess)

mnist = MNIST(train_start=0, train_end=60000)
x_train, y_train = mnist.get_set('train')

fgsm_params = {
    'eps': 0.3,
    'clip_min': 0.,
    'clip_max': 1,
    'y_target': 0
}

for i in range(len(x_train)):
    new_x = attack.generate(x_train[i], **fgsm_params)
    print(x_train[i])
    print(new_x)
    print('\n')
```

However, this results in an error: `AttributeError: 'int' object has no attribute 'get_shape'`

I know this is an easy fix and I hesitate wasting anyone's valuable time to solve it. But if anyone can provide guidance, I would be very grateful.

**Comment by npapernot** [comment]
Thanks for the report. Two things: 

* Could you post this to stackoverflow unless it is a reproducible bug: https://stackoverflow.com/search?tab=newest&q=cleverhans

* Could you paste a full stack trace so we can debug?

From looking quickly at your code, you are using `generate` instead of `generate_np` (the former is for symbolic tensors and the latter for numpy arrays)
