### ISSUE TITLE
Inconsistency between tutorials

### ISSUE THREAD

**Issue by yenchenlin** [tensorflow/cleverhans#292]
I found that `mnist_tutorial_cw.py` and `mnist_tutorial_jsma.py`use function `generate_np` although `mnist_tutorial_tf.py` use `generate` to create adversarial examples.

Though this is rather minor, I wonder is it mean to be like this?

**Comment by carlini** [comment]
The reason it is done this way is because the tf tutorial uses the fast gradient sign attack -- something that is expressed purely in tensorflow. Both JSMA and CW use py_func wrappers, it makes more sense to talk about passing in and receiving numpy arrays. (Or, that's what I assume the reason is. I just copied the JSMA code to get the CW tutorial.)

**Comment by yenchenlin** [comment]
Thanks!
