### ISSUE TITLE
ElasticNetMethod throws error if amount of data not perfectly divisible by batch size

### ISSUE THREAD

**Issue by iamgroot42** [tensorflow/cleverhans#300]
[This](https://github.com/tensorflow/cleverhans/blob/master/cleverhans/attacks_tf.py#L943) line selects 'batch_size' number of examples. However, the batch size is defined for the class object and because of tensor value substitution, an error gets thrown if the variables gets a smaller batch.

For example, if the batch size is 64 and the function is called with 72 samples, the second iteration of the loop throws an error. 

One possible workaround could be to copy the remainder data to fill the batch size and then extract the relevant data while returning.

**Comment by iamgroot42** [comment]
Fixed in https://github.com/tensorflow/cleverhans/pull/301

**Comment by nottombrown** [comment]
@iamgroot42 - It looks like you closed #301. Do you want to close this issue also?

**Comment by iamgroot42** [comment]
@nottombrown no; the issue very much exists. My PR had some conflicts and I don't have the bandwidth to look into it right now. I'll be submitting another PR with the fix soon.

**Comment by npapernot** [comment]
Did you make progress on this? It might make sense to use `batch_eval` or adapt the logic that it implements: https://github.com/tensorflow/cleverhans/blob/master/cleverhans/utils_tf.py#L286

**Comment by goodfeli** [comment]
@ysharma1126 can you implement the fix?

**Comment by ysharma1126** [comment]
This is an issue shared by the C&W attack, so I'm adding @carlini to this thread. 

Personally, I don't feel this issue to be very significant as I don't believe being constrained to set the batch_size to a number perfectly divisble by num_samples (for Non-Targeted Attack) or num_samples*num_classes (for Targeted Attack) makes it difficult to find a batch_size which works for the user's desires. Additionally, if batch_size=1 isn't ideal as speed is an issue, setting batch_size to num_samples (for Non-Targeted Attack) or num_samples*num_classes (for Targeted Attack) still yields good attack performance. 

If the users still feel this issue is significant, I'll attempt to implement a fix as soon as I can.

**Comment by iamgroot42** [comment]
@ysharma1126 it's not about finding a batch_size per se. The current code expects the number of input samples to be **always** divisible by the provided batch size, which is a very bad way to go about it (what if I have 7919 examples?). Setting the batch size to 1, in this case, would be very slow, and the only other batch size you could set is 7919 itself, which I doubt would fit on a GPU for any decently-big model. I'll be implementing a fix soon (hopefully this week) to fix this issue.

**Comment by npapernot** [comment]
Thanks I merged the temporary fix (setting the batch_size to 1) in the meanwhile

**Comment by carlini** [comment]
Something I've done as a workaround: set the batch size to something reasonable (~100), and pad the input by duplicating the last item so that it's a multiple of the batch size. I can submit a fix for this I think by getting the dynamic size of the batch at runtime.

**Comment by ysharma1126** [comment]
@iamgroot42 good points, yes for ease of use a fix should be made. Thanks for your efforts!

**Comment by iamgroot42** [comment]
Implemented a fix in https://github.com/tensorflow/cleverhans/pull/353

**Comment by iamgroot42** [comment]
Issue fixed.
