### ISSUE TITLE
add CIFAR10 tutorial in TF2

### ISSUE THREAD

**Issue by npapernot** [tensorflow/cleverhans#306]
This might require making some changes to the library to support this new mode.

**Comment by KranthiGV** [comment]
@npapernot
Is there any suggested reading/code samples you suggest to look into?

**Comment by npapernot** [comment]
Nothing in mind but I will post resources here if I find any.

**Comment by yenchenlin** [comment]
Hello @npapernot ,

I wrote an easy demo of using FGSM to attack MNIST model [here](https://github.com/yenchenlin/adversarial-example-tf-eager/blob/master/mnist_tutorial_tf_eager.ipynb).

Let me know if this is what you referring to. If so, I will make the code become compatible with cleverhans and submit a PR.

**Comment by npapernot** [comment]
Yes @yenchenlin this is what we are looking for, but if you could adapt the code to use existing CleverHans library functions, that would be better. It might make sense to start a thread on the cleverhans-dev mailing list to make sure that design choices are made collectively if you need to make modifications to the APIs of the CleverHans library. Thank you so much!

**Comment by yenchenlin** [comment]
Hello @npapernot I'll start to adapt my code and open threads on the mailing list if needed, thanks!

**Comment by catherio** [comment]
Hi @yenchenlin - are you working on this? It would still be helpful for us, if you're still up for it!

**Comment by catherio** [comment]
Hi @yenchenlin - since we haven't heard from you, I'm going to re-mark this as "help wanted", but we would definitely still appreciate a contribution from you if you are interested.

**Comment by yenchenlin** [comment]
Hello @catherio , sorry for the late reply. Now I have time to work on it! I was busy in the last few months for grad school 😅.

**Comment by nottombrown** [comment]
Hey @yenchenlin - Let us know if you're working on this and we can mark you as the owner.

**Comment by alexbw** [comment]
Any progress here?

**Comment by goodfeli** [comment]
No progress. I don't think anyone's working on it. It's something I'd consider doing myself but haven't found time yet.

**Comment by goodfeli** [comment]
Thanks! It's probably best to adapt just one of the tutorials though. We don't want to commit to maintaining a lot of duplicated tutorial code.

**Comment by yenchenlin** [comment]
Hello @goodfeli, @npapernot, and @krishnacodes  , sorry for the late reply (in mandatory military so no internet ...)

In my tf-eager ipython notebook example [here](https://github.com/yenchenlin/adversarial-example-tf-eager/blob/master/mnist_tutorial_tf_eager.ipynb), there are two main parts which can potentially reuse the existing code in cleverhans:

1. Model (block **[2]** in notebook)
```
class MNISTModel(tfe.Network):
...
```

2. FGSM (block **[5]** in notebook)
```
def craft_adv(model, dataset):
...
```

For 1., it seems that we can only build model in eager mode either using 1) a subclass of `tfe.Network` or layers defined in `tf.keras`. In cleverhans, we now only have model building code for normal tf and native keras. Should we add new code specific for eager mode? (an example using `tf.keras` which is compatible with eager mode can be found [here](https://github.com/tensorflow/models/blob/master/official/mnist/mnist.py#L33-L86))

And for 2., it's unclear how we can resue the existing code in `attacks_tf.py` since it is based on placeholder. However, eager mode is not compatible with placeholder. Should we just add new methods specific for eager mode in `attacks_tf.py`?

**Comment by npapernot** [comment]
Regarding 1., from experience it has been best to avoid Keras (and we now have managed to isolate most the code related to Keras from the core CleverHans code) so I would be in favor of providing a subclass of `cleverhans.model.Model` for `tf.eager` models.

Regarding 2., if it is too complicated to reuse existing attack classes such as the one here https://github.com/tensorflow/cleverhans/blob/master/cleverhans/attacks.py#L229 then I think it would make sense to start a new thread in the `cleverhans-dev` mailing list to discuss what is the best way to proceed and adapt our API to be compatible with the eager paradigm.

**Comment by feedforward** [comment]
Hi @npapernot i submitted a PR for this 
Regarding 1. A subclass of cleverhans.model.Model is created for eager models.
Regarding 2. A new attacks_eager is added (existing attacks run through session using feed_dict making it too hard to adapt.)

The new eager code is passing all the previous unit tests.(PR)
But test cases i wrote for eager execution are throwing an error in the travis virtual env.
Details: ValueError: tf.enable_eager_execution must be called at program startup.
Travis logs : [https://travis-ci.org/tensorflow/cleverhans/jobs/394798926](url) 

i couldn't reproduce the error in my local machine.(and tests are running without any error.)
if anyone can please run the these tests [https://drive.google.com/drive/folders/1rJOcvJueyxcx1po-nsr4J0Gz5256MIvI?usp=sharing](url) and reproduce the error on travis it will be very helpful.

If the error is not reproducible, is it likely that travis env has a issue with eager exec ?, 
someone faced the same issue with jupyter notebook [https://github.com/tensorflow/tensorflow/issues/18304](url).
