### ISSUE TITLE
Error in tf.while_loop of iterative attacks when using Inception_v3 model 

### ISSUE THREAD

**Issue by Kseniiakv** [tensorflow/cleverhans#907]
Hi everyone, 

Currently I'm trying to attack Inception_v3 model with iterative methods, such as ProjectedGradientDescent and MomentumIterativeMethod. With FGSM everything works fine, but with iterative methods I get an error:

`AttributeError: 'NoneType' object has no attribute 'get_shape'`

The problem is that tf.gradients() function in body of  tf.while_loop() returns None. Everything works fine with ModelBasicCNN model, so I guess  the there is something wrong with my InceptionModel class:

```
from tensorflow.contrib.slim.nets import inception

class InceptionModel(Model):
    def __init__(self, scope, nb_classes, **kwargs):
        del kwargs
        Model.__init__(self, scope, nb_classes, locals())
        self.fprop(tf.placeholder(tf.float32, batch_shape))
    
    def fprop(self, x, **kwargs):
        del kwargs
        with slim.arg_scope(inception.inception_v3_arg_scope()):
            logits, end_points = inception.inception_v3(
                            x_input, num_classes=self.nb_classes, is_training=False, reuse=tf.AUTO_REUSE)

        return {self.O_LOGITS: logits, self.O_PROBS: tf.nn.softmax(logits=logits)} 
```
Using VGG16 architecture instead of Inception gives the same error. I'm new to TensorFlow and I can't figure out how to solve this problem. 
Thank you in advance for your help!

**Comment by goodfeli** [comment]
Something looks weird about the code snippet you pasted. You pass a variable called `x_input` to `inception_v3` but there is no `x_input` variable defined anywhere.

My guess is that in your own repo, `x_input` is a global variable. FGSM works because it only ever makes one call to fprop, and on that call the `x` argument to `fprop` happens to be `x_input`. The iterative versions fail because on the second iteration, `x` is no longer the same as `x_input`, and the loss has no derivative wrt `x_input` if you're using a `stop_gradient` on each iteration.

If my guess is correct, you should change "logits, end_points = inception.inception_v3(x_input," to "logits, end_points = inception.inception_v3(x,".

Feel free to re-open the issue if I have not guessed correctly.
